### ISSUE TITLE
起動時の画面作成

### ISSUE THREAD

**Issue by datsuns** [datsuns/ranmelo#6]
設定と、動作の開始を指定する時の画面を作成する

**Comment by ghost** [comment]
リストビューで一覧つくる

**Comment by ghost** [comment]
http://www.adakoda.com/android/000077.html

**Comment by ghost** [comment]
作業ブランチ
make_settting_view

**Comment by datsuns** [comment]
追加する処理
- 画面は以下の構成
  - 一番上に「開始」「キャンセル」のボタンを配置
  - ボタンの下に着信音の一覧が出る
- 今のところは着信音の一覧を選択しても何もしないが、選択した際のハンドラの枠だけ作成しておく

**Comment by datsuns** [comment]
着信音の格納先は以下の二つ。
- /sdcard/media/audio/ringtones
- /system/media/audio/ringtones
